### ISSUE TITLE
Configure Keycloak integration with Management and Task Console on Openshift/K8s environments

### ISSUE THREAD

**Issue by caiomedeirospinto** [apache/incubator-kie-kogito-apps#1156]
Hi community,

I'm trying to make travel example run into an Openshift 4.7.38 environment (Kubernetes v1.20.11+aa025a0), I was able to deploy whole pieces but management and task console don't work, when I try to use them they show an error to integrate with SSO.

Screenshot:

<img width="1680" alt="Screen Shot 2021-12-13 at 12 09 49" src="https://user-images.githubusercontent.com/28579786/145837250-96e5a4c6-005a-4b51-86ea-2092a7c367c9.png">

I already tried to configure the following environment variables:

* KOGITO_CONSOLES_KEYCLOAK_URL
* KOGITO_CONSOLES_KEYCLOAK_HEALTH_CHECK_URL
* kogito.consoles.keycloak.config.url
* KOGITO_CONSOLES_KEYCLOAK_CONFIG_URL
* kogito.consoles.keycloak.config.health-check-url
* KOGITO_CONSOLES_KEYCLOAK_CONFIG_HEALTH_CHECK_URL

Ate the end nothing worked, so I think that I must not be the first one that wanna deploy it over an Openshift environment, there are somebody that already fix it?, if not, how do you think it can be fixed?

**Comment by r00ta** [comment]
Hi @caiomedeirospinto , yes you should set the following env variables in the kubernetes `Deployment`: 
- `KOGITO_CONSOLES_KEYCLOAK_CONFIG_URL`
- `KOGITO_CONSOLES_KEYCLOAK_CONFIG_CLIENT_ID`
- `KOGITO_CONSOLES_KEYCLOAK_CONFIG_REALM`
- (see all the properties here https://github.com/kiegroup/kogito-apps/blob/main/management-console/src/main/resources/application.properties)

Could you paste here the `Deployment` resource you are deploying?

**Comment by caiomedeirospinto** [comment]
I deleted it to recreate but now it's not coming up, basically operator doesn't create the deployment. I'm trying to do it from the beginning to find the error, as soon it become deployed again I'll share you the deployment yaml.

**Comment by caiomedeirospinto** [comment]
Ready!, I had to restart operator pod many timer to force him create the deploy (I'm trying to solve this issue [here](https://github.com/kiegroup/kogito-operator/issues/1090)). Anyway, here are my deployment yaml:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"kogito-management-console:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"management-console\")].image"}]
  selfLink: /apis/apps/v1/namespaces/caio/deployments/management-console
  resourceVersion: '14941368'
  name: management-console
  uid: 7827281e-e440-4ed8-99da-d899014ff090
  creationTimestamp: '2021-12-13T17:08:03Z'
  generation: 1
  namespace: caio
  labels:
    app: management-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-console
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: management-console
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: management-console
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: RUNTIME_TYPE
              value: quarkus
            - name: KOGITO_DATAINDEX_HTTP_URL
              value: 'http://data-index-caio.apps.florestal-01.latam-1.rht-labs.com'
            - name: KOGITO_DATAINDEX_WS_URL
              value: 'ws://data-index-caio.apps.florestal-01.latam-1.rht-labs.com'
            - name: KOGITO_CONSOLES_KEYCLOAK_CONFIG_URL
              value: >-
                https://keycloak-caio.apps.florestal-01.latam-1.rht-labs.com/auth/
            - name: KOGITO_CONSOLES_KEYCLOAK_CONFIG_CLIENT_ID
              value: kogito-console-quarkus
            - name: KOGITO_CONSOLES_KEYCLOAK_CONFIG_REALM
              value: kogito
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: management-console-properties
          image: >-
            image-registry.openshift-image-registry.svc:5000/caio/kogito-management-console@sha256:9ca593ef48689ccda6df937a73bfe8e24de32a75d81e9ad7b91e476f1e011c7f
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

It keeps not working, even with the environments that you mentioned.

**Comment by caiomedeirospinto** [comment]
I solved!!!, it was missing the env KOGITO_CONSOLES_KEYCLOAK_CONFIG_HEALTH_CHECK_URL, I configured it and it worked!!. Thanks @r00ta for held me a hend with this!!! U R AWESOME!!!

**Comment by r00ta** [comment]
Glad it worked out @caiomedeirospinto . I'm not the operator expect but at a first glimpse I guess the operator should have set it: maybe there is a bug. Could you double check @ricardozanini or @sutaakar (or anybody else)?

**Comment by sutaakar** [comment]
There is a bug in operator, see [linked issue](https://github.com/kiegroup/kogito-operator/issues/1090) for details.

**Comment by pefernan** [comment]
Looks like I arrived late here... good to see that @caiomedeirospinto already solved the issue. Just mention that that `KOGITO_CONSOLES_KEYCLOAK_CONFIG_HEALTH_CHECK_URL` is used to do a healthcheck of the keycloak server before entering the console. Just for the sake, tt's possible to disable that check by setting the `KOGITO_CONSOLES_KEYCLOAK_CONFIG_DISABLE_HEALTH_CHECK` to true.

**Comment by r00ta** [comment]
@sutaakar @pefernan how should the user configure those when using the kogito operator?

**Comment by sutaakar** [comment]
Currently user needs to set proper env variables in `KogitoSupportingService` custom resource. Or the env variables can be placed in ConfigMap, which is then referenced in `KogitoSupportingService`.

**Comment by doogle-oss** [comment]
Anything on not using keycloak as OIDC provider??
