### ISSUE TITLE
Unable to set authorized actors/groups for starting a process/bpmn?

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-kogito-apps#1200]
### Description

User tasks have authorization, but it is unclear from the docs: Can authorized actors/groups be set un the process modeler for who is allow to start a process?

**Comment by cristianonicolai** [comment]
@StephenOTT I think it is a little hidden in the docs, but check this section: https://docs.kogito.kie.org/latest/html_single/#proc-bpmn-model-creating_kogito-developing-process-services
More specifically where it mentions process metadata. You can add a metadata attribute to the process named `securityRoles` and in there you can add a list of comma separated list of roles that you would like to restrict access to. From there, is up to your application security mechanism.

**Comment by StephenOTT** [comment]
Thanks.
