### ISSUE TITLE
Data index do not register array for repeated proto object

### ISSUE THREAD

**Issue by doogle-oss** [apache/incubator-kie-kogito-apps#1319]
### Describe the bug

As per kogito docs it supports 
Java object with list of Java object.
When proto is generated it generate correctly list as repeated object.
In data index however it does not create schema as array and register scham witht he object only. Advice on this.

### Expected behavior

If a variable is
`Public class Samples{
   private List<Sample> smp;
}`

The the data index should register smp as a array

### Actual behavior

Only single sample object is created in schema.

### How to Reproduce?

Try a simple variable with list of Java object inside and try registering in data index.

### Output of `uname -a` or `ver`

Mac mini arm chipset

### Output of `java -version`

Graal vm 22

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

1.20.0.Final

### Additional information

Need to register the list if proto have repeated value.

**Comment by doogle-oss** [comment]
@evacchi @cristianonicolai please advise

**Comment by nmirasch** [comment]
@debu999 I'm taking a look

**Comment by nmirasch** [comment]
Even runtime is able to handle such collections, data-index is not processing them as a repeatable fields. I've created this jira to track this. https://issues.redhat.com/browse/KOGITO-7077 
Thanks @debu999 for bring this up!

**Comment by nmirasch** [comment]
@debu999 support for collections in datai-ndex have been added in 1.22 release
