### ISSUE TITLE
InvalidSchemaException when registered a proto which has only one variable in the message.

### ISSUE THREAD

**Issue by prerana15** [apache/incubator-kie-kogito-apps#1422]
### Describe the bug

in kogito bpmn, I added a process variable (for example "travels" variable) of type Java class(which has only one variable of type List)
when I register the kogito generated proto in dataindex and try to run the application, I get InvalidSchemaException exception.

This exception goes away when I add more variable in the Java class along with List type variable.
But as per our requirement we want only one variable in that java class.

### Expected behavior

data index should start without any exception.

### Actual behavior

Data index start up is failing because of InvalidSchemaException: TravelsOrderBy must define one or more field.

### How to Reproduce?

1. Create a Java class with one variable.
public class Travels{
private List<Travel> travels;
}
public class Travel{
private String travelId;
}

2. Add a process variable in bpmn of type Travels class
3. generate proto and register it in data index.
Sample:
/*Indexed*/
message Travels{
options java_package = "some package";
repeated Travel travels = 1;
}
4. Start the application

### Additional information

Since List datatype is not supported in kogito bpmn. We had to wrap the List type variable inside a Pojo. and hence we have only one variable in the POJO.

**Comment by prerana15** [comment]
Any update on this one?

**Comment by cristianonicolai** [comment]
@prerana15 can you share the full proto? I'm missing the `metadata` attribute in your example.

**Comment by cristianonicolai** [comment]
Created https://issues.redhat.com/browse/KOGITO-7690 to track this issue.
