### ISSUE TITLE
task-console quarkus.kogito-runtime-tools.users

### ISSUE THREAD

**Issue by kstan79** [apache/incubator-kie-kogito-apps#1549]
### Describe the bug

I'd install quarkus.kogito-runtime-tools.users, and configured the user list however only `admin` shown:

<img width="1703" alt="Screenshot 2022-12-06 at 2 07 54 PM" src="https://user-images.githubusercontent.com/1889979/205834665-eeffa054-0a14-41fc-b4f7-caaa93a7d9ae.png">

[edit] Plenty of javascript error:
<img width="1665" alt="Screenshot 2022-12-06 at 2 42 30 PM" src="https://user-images.githubusercontent.com/1889979/205840060-8d98b99a-d401-4047-9dbc-c6cc8d524a55.png">

application.properties defined list of users but not detected:

```
quarkus.kogito-runtime-tools.users=jdoe,user,admin
quarkus.kogito-runtime-tools.users.jdoe.groups=admin
quarkus.kogito-runtime-tools.users.admin.groups=admin
quarkus.kogito-runtime-tools.users.user.groups=user
```

### Expected behavior

by right drop down should show 3 users "jdoe,user,admin"

### Actual behavior

only admin shown

### How to Reproduce?

1. install runtime-tools-quarkus-extension:  run cli: `quarkus extension add runtime-tools-quarkus-extension`
2. run `quarkus dev`
3. browse to http://localhost:8080/q/dev/org.kie.kogito.runtime-tools-quarkus-extension/tasks

### Output of `uname -a` or `ver`

Darwin kstans-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 19.0.1 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk 19.0.1 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

powered by Quarkus 2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by ricardozanini** [comment]
@pefernan can you please take a look?

**Comment by pefernan** [comment]
@kstan79 thanks for reaching us with this issue. Actually this is happening because of a change on the Quarkus API that made us change the key to define the extension users and groups in the `application.properties`. The right format should be `kogito.users.{user}.groups={comma_separated_list_of_groups}`. For example something like:

```
kogito.users.jdoe.groups=admin
kogito.users.admin.groups=admin
kogito.users.user.groups=user
````

Notice that right now we don't have a specific property to setup the users list (the old `quarkus.kogito-runtime-tools.users`), so with a single line we configure the user and it's groups.

We are already updating the documentation with the solution and the PR is already sent.

Thank you!

**Comment by kstan79** [comment]
wow, nice. tqvm!

**Comment by ricardozanini** [comment]
@pefernan can you please link the PR here?

**Comment by pefernan** [comment]
@ricardozanini here we go: https://github.com/kiegroup/kie-docs/pull/4375 It's already approved, so it can be merged I guess.

**Comment by kstan79** [comment]
nice! you guys like hero. 
it work after use new properties
<img width="1753" alt="Screenshot 2022-12-14 at 10 35 58 PM" src="https://user-images.githubusercontent.com/1889979/207624086-d790d514-1b64-4909-8d23-96d942700f98.png">
