### ISSUE TITLE
Java data type "Long" is registered as "int64" in Proto in data index.

### ISSUE THREAD

**Issue by prerana15** [apache/incubator-kie-kogito-apps#1561]
Java data type "Long" is registered as "int64" in Proto in data index. This is giving issue while we are trying to access Long value in DI.
For example if 
Long a = 313243691345678
It's giving error "Expected type Int, found 313243691345678"

**Comment by radtriste** [comment]
@cristianonicolai can you have a look ?

**Comment by nmirasch** [comment]
Hello @prerana15,  AFAIK the int64 is big enough to handle long values. Could you provide more details about the environment and  error thrown, do you have any logs that can help to investigate what is happening? Thanks!

**Comment by doogle-oss** [comment]
@nmirasch find the details of findings
1. Dataindex recognise long field correctly. see below paramA is Long type.
![Screenshot 2022-12-15 at 8 22 17 AM](https://user-images.githubusercontent.com/1910577/207761681-adcb0548-711b-45b5-a968-d02fad2b803b.png)
While building inputArgument it translates to NumericArgument which is having the bug as it translates to Int only.
We should update the NumericArgument to Long then it should resolve else we need to add in a LongArgument.
![Screenshot 2022-12-15 at 8 21 58 AM](https://user-images.githubusercontent.com/1910577/207761910-2b150c48-b0c2-4d12-8428-f4990535903c.png)
![Screenshot 2022-12-15 at 8 21 24 AM](https://user-images.githubusercontent.com/1910577/207761925-b65832bb-897a-4cd4-9ec5-0a99e608e054.png)
![Screenshot 2022-12-15 at 8 22 47 AM](https://user-images.githubusercontent.com/1910577/207761957-c59381a3-62dd-4d8d-9158-0eb0793b00da.png)
![Screenshot 2022-12-15 at 8 22 57 AM](https://user-images.githubusercontent.com/1910577/207761960-b285fcc5-c106-4988-b529-7232f8807981.png)
![Screenshot 2022-12-15 at 8 23 04 AM](https://user-images.githubusercontent.com/1910577/207761961-5fac7ab1-acf6-49cd-8eb3-6fa89cde545d.png)

**Comment by doogle-oss** [comment]
in schema.graphqls we have the following
```
input NumericArgument {
    in: [Int!]
    isNull: Boolean
    equal: Int
    greaterThan: Int
    greaterThanEqual: Int
    lessThan: Int
    lessThanEqual: Int
    between: NumericRange
}

input NumericRange {
    from: Int!
    to: Int!
}
```
the translation causes issue may be we can do Long instead of Int

**Comment by doogle-oss** [comment]
Possible solution is to use Float but it will have exact match issues due to precision or register a new input scalar for long

**Comment by nmirasch** [comment]
@debu999 Thank you very much  for the details, Would you mind to fill a jira to be able to prioritze this?

**Comment by doogle-oss** [comment]
https://issues.redhat.com/browse/KOGITO-8375 raised for this.

**Comment by prerana15** [comment]
@nmirasch - any update on this?

**Comment by nmirasch** [comment]
Hello @prerana15 @debu999, We are adding support for Long/Float/Double with their specific GraphQL type in https://github.com/kiegroup/kogito-apps/pull/1593. From that code, type Long type will be registered as specific GraphQL Long type instead int64.

**Comment by prerana15** [comment]
Thank you @nmirasch 😊
