### ISSUE TITLE
Support for Java Primitives or Simple Data Types

### ISSUE THREAD

**Issue by doogle-oss** [apache/incubator-kie-kogito-apps#1571]
At present the only supported Java Primitives are
1. String
2. Boolean
3. Numeric Just Integer - Range:  -2147483648 to 2147483647
4. DateTime (java.util.Date)

There are standard primitives which are not supported yet.
(Non Blocker) byte -> its actually supported with Integer but can be helpful for memory utilization if added. range -128 to 127 
(Non Blocker) short -> 16-bit so -32768 to 32767 can be modelled under Integer which is supported
(Blocker) long -> -9223372036854775808 to 9223372036854775807 This is currently not supported
(Blocker) float -> 32-bit IEEE 754 floating point
(Blocker) double -> double-precision 64-bit IEEE 754 floating point
(Non Blocker) char -> single 16-bit Unicode character can use String for this.

**Comment by doogle-oss** [comment]
Atleast Int getting updated to Long and a support for Double will suffice all the datatypes but ideally if first hand support is added for the 5 missing data types it will enhance user utilization of the framework efficiently.

**Comment by doogle-oss** [comment]
@cristianonicolai @nmirasch Looking to your guidance as these can be modelled in the framework easily i believe.

**Comment by doogle-oss** [comment]
```
url -X 'POST' \
  'http://localhost:8080/dataindexdate?businessKey=d1' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "dt": "2022-03-10",
  "input": {
    "param": "d1",
    "paramA": 1234555,
    "paramB": 8721398745987389.84
  },
  "abc": "d1"
}'
```

float gets stored as string in dataindex and in kogito
and moreover kogito runtime do not have support for double/float.
![Screenshot 2022-12-20 at 10 00 47 AM](https://user-images.githubusercontent.com/1910577/208584160-abd06ac0-f406-44a8-9ae2-1e079eefe75d.png)


Input: 
Date timezone is UTC or +00:00 but since the data type support is
{
  "dt": "2022-03-10T12:00:45.087+00:00",
  "input": {
    "param": "d4",
    "paramA": 12345557464,
    "paramB": 87213987459873576.956
  },
  "abc": "d4"
}

**Comment by ricardozanini** [comment]
@cristianonicolai @nmirasch

**Comment by doogle-oss** [comment]
is this being worked upon?

**Comment by doogle-oss** [comment]
any update done in the storage apis for fixing conversion issue in kogito mongodb.

**Comment by nmirasch** [comment]
Hello @debu999, We are adding support for Long/Float/Double with their specific GraphQL type  in  https://github.com/kiegroup/kogito-apps/pull/1593 and that improves the precision when getting the stored values from database.

**Comment by nmirasch** [comment]
@debu999 regarding the 'blocker' types are now supported, could we close this issue. In the other types are required too, feel free to fill a jira for that and be included in TODO list when it can be possible. Thanks!

**Comment by doogle-oss** [comment]
Thanks @nmirasch we can close this. About to test in upgraded version now
