### ISSUE TITLE
Duplicated information in the `variables` object

### ISSUE THREAD

**Issue by caponetto** [apache/incubator-kie-kogito-apps#1989]
### Describe the bug

Sometimes when `variables` are fetched from the Data Index, there is duplicated information in the response.

### Expected behavior

I'd expect simply:
```json
"variables": {
  "workflowdata": {
    "myKey": "myValue",
    "mantra": "Serverless Workflow is awesome!",
    "greeting": "Hello World"
  }
}
```

### Actual behavior

If you fetch the `variables`, you'll get:
```json
"variables": {
  "workflowdata": {
    "myKey": "myValue",
    "mantra": "Serverless Workflow is awesome!",
    "greeting": "Hello World"
  },
  "workflowdata.mantra": "Serverless Workflow is awesome!",
  "workflowdata.greeting": "Hello World"
}
```

See that `mantra` and `greeting` are duplicated.

### How to Reproduce?

Take the [Hello World workflow](https://github.com/apache/incubator-kie-kogito-examples/blob/stable/serverless-workflow-examples/serverless-workflow-hello-world/src/main/resources/hello.sw.json) as an example and execute it with additional inputs, for instance:
```json
{
    "myKey": "myValue"
}
```

**Comment by fjtirado** [comment]
In addition to the problem described, internal variables should not be published
