### ISSUE TITLE
Use of Apache ActiveMQ or AMQP instead of Kafka

### ISSUE THREAD

**Issue by indiealexh** [apache/incubator-kie-kogito-apps#222]
I don't see any blocker to this but I wanted to see if there were any technical reasons not to do this.

My current Quarkus project currently uses Apache ActiveMQ, and I would rather avoid needing to deploy Kafka AND ActiveMQ, **Can I just change the application.properties and make Kogito Data Service use AMQP instead?**

**Comment by indiealexh** [comment]
I am in a similar position. We use ActiveMQ as the use of Acknowledgements is important for some more critical data (At the cost of speed).

I don't see anything that would prevent me from doing this, but any guidance on why or why we should not use something other than Kafka for this service would be useful.

**Comment by cristianonicolai** [comment]
@indiealexh not as simple as changing the application.properties at this point, especially because it would be still missing the SmallRye dependency for ActiveMQ. You can probably give it try if that would work by adding a new dependency to the data index project.
