### ISSUE TITLE
Task instance diagram is not displayed on management console

### ISSUE THREAD

**Issue by rbaumgar** [apache/incubator-kie-kogito-apps#743]
see https://github.com/kiegroup/kogito-examples/issues/634#issue-846958562

**Comment by nmirasch** [comment]
@rbaumgar The management console only shows the process instance diagram. 
But related to your comment related with the doc.. yes,! I see there is a typo in the path. good catch, Thanks!
Currently, the available REST endpoints provided by the process SVG add-on are:
1. [GET] /svg/processes/{processId} Retrieve just the process diagram
2. [GET] /svg/processes/{processId}/instances/{processInstanceId}  (without the /nodeinstance at the end) To get  the process instance execution highlighted path in the diagram 
I've created https://issues.redhat.com/browse/KOGITO-5392 to track the change at the doc.

**Comment by nmirasch** [comment]
Documentation change have been incorporated by.. https://github.com/kiegroup/kie-docs/pull/3715
